# Autogenerated by devscripts/update-version.py

__version__ = '2023.12.22.174241'

RELEASE_GIT_HEAD = '6a26ecc143eda8febdd8467d4c72573831144bca'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'deep-soft/yt-dlp'

ORIGIN = 'deep-soft/yt-dlp'

_pkg_version = '2023.12.22.174241'
