# Autogenerated by devscripts/update-version.py

__version__ = '2023.11.21.141530'

RELEASE_GIT_HEAD = 'a9f90a7e33e510cc2e235b01c240b12621188f6a'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'deep-soft/yt-dlp'

ORIGIN = 'deep-soft/yt-dlp'

_pkg_version = '2023.11.21.141530'
