# Autogenerated by devscripts/update-version.py

__version__ = '2024.09.16.125415'

RELEASE_GIT_HEAD = '11875b4c86d396ccd3968414b9e14e4558b649df'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'deep-soft/yt-dlp'

ORIGIN = 'deep-soft/yt-dlp'

_pkg_version = '2024.09.16.125415'
